getting-started/002-search.md
getting-started/004-reverse.md
getting-started/005-place.md
getting-started/006-response.md
transition.md

Revises all example URLS to point to search.mapzen.com over SSL

Final URLS

---

search.md

Rolling this back, as image links are updated in PR #27 and have ALT text in those changes. I will add the multiple boundary image to PR#27.

Revert "Fix image links"

---

index.md

file was renamed, needed to update link
spotted by @drewda (thanks!)

Fix broken API key link

---

data-sources.md

Revise all data source descriptions to follow a common pattern:
1.) What, in brief, is it?
2.) Why is it useful to include in Mapzen Search?
3.) What is the license?
I'd love some further help with tweaks in a couple areas that I think
are still lacking:
* keeping it informative without sounding too sales-pitchy. I really
want to list the good reasons why we use each data source without making
it sound like we are trying to sell someone something they don't need.
* Following the common format without sounding too templated
* Not hating on Geonames. It's a good dataset and we include it for a
reason, but it is a bit different and we also want to capture that
honestly.
Fixes #26

Add usage data and license info to all data source docs

---

index.md

Looks like we forgot to link to this on the index page

Add link to responses document

---

response.md

Add some descriptions to various parts of the response:
* GID
* Label
* Confidence
Helps answer #36.

Describe notable response features

---

search.md

Addresses issue #40 from @riordan 
(Size was missing from Search topic, but is already there in Reverse topic.)

Add size parameter description

---

glossary.md

Here's a start to the glossary of common terms in Mapzen Search. See issue #10
Please review and commit more edits and terms, as needed.
Note: This PR contains only the glossary file, not the other changes in PR #45.

Add glossary file

---

index.md

New topic, new link on page
Also did some formatting changes for doc site

Add glossary to index page

---

use-cors.md

mention the leaflet plugin
please review @rmglennon

mention the leaflet plugin

---

http-status-codes.md
index.md

documentation for http status codes
review please @rmglennon

documentation for http status codes

---

index.md

Trying out not including the topic bullet list because it's duplicated with the TOC on the doc website.
Will see if it makes sense to add a topic list for people who are reading the help on GitHub.

Rework index for help system

---

place.md

Added a little text in there about excluding datasets. Resolves https://github.com/pelias/pelias-doc/issues/19

Clarify multiple place search

---

LICENSE.md

Changes license from MIT (Code) to CC-BY-4.0 (for Creative Works)

---

place.md
response.md

Update /place endpoint ids info

---

installing.md

Suggestions from @rmglennon 
Fixes #55

Installation tweaks

---

installing.md

updated a broken link and added extra install info about WOF, pulled from that particular module.

installation docs edit

---

release-notes.md

June 13 release notes

---

release-notes.md

Wow! So many changes!
Obviously we won't merge this until after we release tomorrow :)

Release notes 2016-08-02

---

autocomplete.md

Connects https://github.com/pelias/pelias/issues/403

Add boundary.country section and info to autocomplete docs

---

release-notes.md

Release notes 2016-08-22

---

installing.md

We list a lot of version numbers and datsaset sizes, they need to be periodically kept up to date. Moar data!

Tweak numbers

---

add-search-to-a-map.md
api-keys-rate-limits.md
autocomplete.md
place.md
response.md
reverse.md
search.md
transition-from-beta.md
use-cors.md

edit keys in _every demo_ to reflect new unified keys

add unified keys

---

installing.md

We have made progress on making importers more consistent!
Metro extracts has also gotten better!

Update installation docs

---

use-cors.md

updating the demo links for leaflet geocoder

update CORS page

---

installing.md

Connects https://github.com/pelias/schema/issues/178

Add section on Elasticsearch config (and shards)

---

release-notes.md

Release notes 2016/10/24

---

search.md

It was implied that the granularity ranged from fine to coarse.

Fixed order in layer chart

---

release-notes.md

This includes a note that we don't have any new data this week. Otherwise its the same as https://github.com/pelias/pelias/pull/476

Mapzen Search Release notes for December 5th

---

data-sources.md

it's now over 300 million records! 🎉

update OA from 200 to 300 million!

---

circle.yml

Part of https://github.com/mapzen/mapzen-docs-generator/issues/243

Updated tickler config for new docs repository name

---

release-notes.md

jan 27 release notes

---

language-codes.md

docs for feature https://github.com/pelias/api/pull/819
do not merge at this time as the feature has not been rolled out to production.
editorial review and edits welcome.

docs for language codes

---

glossary.md
search-workflows.md

Fixes https://github.com/pelias/pelias-doc/issues/155 (for real)
This is a modified version of a blog post. I'm adding it to the docs to make it easier to find, more permanent, and reviewed frequently.

Add "which endpoint when" topic to help

---

release-notes.md

Release notes 2017-08-22

---

README.md
development_roadmap.md

A list of the most important features we'll be working on in the future.

Development Roadmap

---

requirements.md

Connects https://github.com/pelias/pelias/issues/752
Connects https://github.com/pelias/pelias/issues/461

Update Node.js and Elasticsearch requirement

---

development/roadmap.md
full_planet_considerations.md

We've made considerable improvements in best practices for running Pelias, and improved elias performance, in the past few months. :tada: 
This updates the full planet build considerations to reflect the latest advice and expectations.

Update hardware requirements

---

full_planet_considerations.md
pelias_from_scratch.md

Update our numbers and recommendations for full planet builds.

Full planet doc updates

---

autocomplete.md
search.md

Postalcode where missing in the layer list for autocomplete and search.
Fixes: #212

Add postalcode layer in autocomplete and search

---

autocomplete.md

These are very useful, but were missing a few key details. The formatting is also improved.

Expand autocomplete UX guidelines

---

autocomplete.md

Related to https://github.com/pelias/pelias/issues/746.

Include size for autocomplete

---

autocomplete.md
reverse.md
search.md

Doc for multi `boundary.country` query parameter (pelias/api#1281)

---

autocomplete.md

https://github.com/pelias/api/pull/1278

Update docs for boundary radius on autocomplete.

---

pelias_from_scratch.md
requirements.md

Update recommended elasticsearch version

Update recommended elasticsearch version

---

response.md
reverse.md

Fix documentation on distance units
