pelias/documentation

- getting-started/000-getting-started.md
- getting-started/001-api.md
- getting-started/002-search.md
- getting-started/003-reverse.md
- getting-started/004-place.md
- getting-started/005-response.md
Main changes:
Formatting updates to be more friendly to mkdocs pipeline
Voice changes to match doc style
Moved results from search topic to response topic
To do:
description of the data sources used in Mapzen Search
more on layers - perhaps pull layers and data sources into a separate topic and link to it from the 002-search topic
working examples and API keys
more on the overview
If you don't want to merge this to master at this time, we can work off rhonda-doc-updates branch.
---
Some editing comments:
- Make topic and section titles be Sentence case, using imperative verbs (such as “Getting Started with Mapzen Search” should be “Get started with Mapzen Search”)
- Need a # (no == under titles) for the main title, and then ## or more for subheadings. Try to limit to ### levels to keep …
> First pass through Search docs

- getting-started/007-misc.md
- getting-started/007-using-cors.md
For security reasons, web browsers prevent what are called “cross-origin” or “cross-site” requests from one domain to another. JavaScript `XMLHTTPRequests` (commonly called “AJAX” requests) inherit all of the authentication context of the currently logged in user, so a malicious web page could attempt to make malicious requests that cross domain contexts and cause trouble. Historically, that has made it difficult for web developers to build web applications making use of third-party APIs.
Fortunately, techniques have since been developed that allow developers to securely access APIs cross-domain.
`CORS` is the recommended standard for allowing your web browser and a web server to negotiate and allow requests to be made across domain contexts. `CORS` is currently supported in modern …
> Cross-Origin Resource Sharing

- README.md
- transition.md
MKDocs generates project documentation from an `index.md` file. Github defaults to a README.md to display on the project page. Lets make these two be friends.
The good news is Github will happily read an aliased README.me, so when we turn on MKdocs, we get the best of both worlds.
> Symlink index.md -> README.MD

- transition-from-beta.md
As the Mapillary folks noted, we didn't explicitly mention the new domain nor the /v1/ URL namespace in this document. Whoops.
> added in note about new domain and v1 to transition documentation

- api-keys-rate-limits.md
add documentation about the rate limiter behaviour
resolves: https://github.com/pelias/pelias-doc/issues/50
review please @rmglennon (this will be the same across all mapzen services)
**note:** viewing the error messages in your browser will render them as `XML`, this is due to most browsers sending a header such as `Accept:text/html,application/xhtml+xml,application/xml`, if you want to see `JSON` you'll need to send a header such as `Accept:application/json` instead
> add documentation about the rate limiter behaviour

- add-search-to-a-map.md
Some of the text was written specifically for Maptime Oakland. Pulled out the Oakland info and API key we provided and replaced with instructions to get your own key.
Also fixed some persnickety formatting issues visible when it's posted on the docs site.
> Generalize tutorial scenario, add api key info

- search.md
Update search.md to add example to layers.
[edit from missinglink] matt noted that it was not clear that you can specify multiple layers by using a comma to delimit them.
> Update search.md to add example to layers

- add-search-to-a-map.md
The geocoder plugin 1.4.0 published today. biggest change is to help people use the plugin from cdn with one line of code by assuming that paths to point/polygin icons are wherever the plugin is loaded from, not where the current page is. https://www.npmjs.com/package/leaflet-geocoder-mapzen
--
As part of this, I updated the URLs to 1.4.0 and rolled back a change that was previously needed to make the icons display if they are not installed locally. With 1.4.0, we can use one line of code to add a search box.
> Change cdn release number, roll back some icon changes

- search.md
Fixes geonames abbreviation (is `gn`, but was written `ga` in one document).
Good catch by @msmollin in pelias/pelias#261
Fixes pelias/pelias#261
> Revises Geonames abbreviation

- data-sources.md
There needs to be a blank line between the heading and the bullet list items underneath. GitHub-flavored markdown is able to render this properly, but not the parser used in the documentation.
Also, changing the e.g. to "for example"
> Make bullets be formatted properly

- installing.md
These are full instructions for setting up Pelias (not Mapzen Search) manually. It's intended mostly to be educational, since ideally people can automate much of this with Chef scripts or the Vagrant image. However, we haven't yet been able to publicize our Chef scripts, and the Vagrant image hasn't gotten a ton of love lately, people may end up following it all the way through.
> Installation docs

- data-sources.md
This makes it more obvious how we're handling the deprecation
> Add a note about sources containing quattroshapes

- add-search-to-a-map.md
- autocomplete.md
- place.md
- response.md
- reverse.md
- search.md
Fixes #108.
Following discussion with @migurski and in issue #108, I made a new GitHub account for use in documentation and created new keys. We can rotate these periodically or change their limits as needed. I will monitor the usage.
Some keys should still remain placeholders, so I did not do an automatic "replace all" in the files. I left the tutorial and the generic examples in Search enpoint, for example.
Other fixes:
- made all the links consistently formatted (some started with full URL, others v1)
- added bold formatting around certain parts of the URL to show specific capabilities being described
- made a few minor formatting or wording changes
There's likely a prettier way we can make these examples, but the key now is that they should all work.
(side note, I accidentally pushed …
> Make example query links work

- installing.md
including heap size info, 
Also minor quibble on line 112, the address_dedupe libarary currently used does *not* use libpostal as far as I can tell. I believe it uses the earlier address_normalize library, which has since been depreciated.
> specifics about ES

- index.md
Original: "Plug-in for embedding search in a Leaflet-based maps". Map shouldn't be plural and I linked to Leaflet as its the first time its referenced in the docs
> fix grammar and add leaflet link

- autocomplete.md
- data-sources.md
- reverse.md
- search.md
We periodically add new layers to various data sources, and we've been bad at updating the docs. These changes bring all the layer lists that I could find up to date, and makes them more consistently formatted between endpoints.
Fixes pelias/api#484
> Update and make the list of layers consistent

- installing.md
While we haven't yet made Node.js 4 required in all code, it's probably
best to start with documentation, letting people know ASAP, and then
roll out the version requirement change later.
Connects https://github.com/pelias/pelias/issues/404
> Update Node.js requirement to 4.0 or greater

- installing.md
It's all mentioned as optional for now, but perhaps soon we'll want to make it required.
> Add libpostal installation instructions

- addresses.md
This adds a new topic that discusses address search results and fallback behavior. In the future, we can add docs on how to specify an address in chunks (5 box).
Note: there is not currently a link to libpostal. I'll add it in when I get its API docs on the website, unless there is a better one for now.
Also, hooray, I wrote this one without using Pelias or Mapzen Search terms.
@trescube - this has some intro content on confidence, accuracy, and match types, if any of that is useful for your post.
cc @dianashk
> add address searching topic for libpostal release

- response.md
These note that we use longitude, latitude order.
@rmglennon, @dianashk I was thinking of adding more about our plans to eventually return polygons in this section. Do you think that would fit in here? Update: I don't think it would. Would still love to hear thoughts though.
Fixes pelias/pelias#441
> Add coordinate section to API response docs

- data-sources.md
openaddresses sources shorthand was incorrectly indicated as `sources=osm`
> fix openaddresses sources typo

- installing.md
Using the git repo and setting up git-lfs, or using the bundles
manually, is too error prone compared to just using the downloader.
> Remove mentions of ways to get WOF data other than the downloader

- autocomplete.md
- search.md
There was a list of all parameters accepted by the autocomplete endpoint (which was out of date, I updated it), but not for search.
This PR adds a list of all supported search endpoints.
> Add search parameter list

- circle.yml
This change adds Pelias docs to Mapzen’s docs pipeline, so that successful master commits here trigger a fresh documentation publish process and no one needs to wait for docs to go live.
Part of https://github.com/mapzen/mapzen-docs-generator/issues/224.
> Added no-tests Circle file to join the docs pipeline

- search.md
- structured-geocoding.md
Adds new topic for structured (needs final blog content copied in, as this is kind of a page dump)
Adds some content into search (although it feels kind of bolted on, as all the examples are of text parameter
Depends on https://github.com/mapzen/mapzen-docs-generator/pull/236
> Add structured geocoding docs

- add-search-to-a-map.md
- search.md
JSONView has been removed from the Chrome web store because of a security issue. 
Some folks are using JSON Formatter as a replacement, but it is also an older tool. Let's remove the specific product reference here.
> Remove reference to JSON-formatting browser plug-ins

- swagger-docs/pelias-v1-api-swagger.yml
Adds in missing autocomplete params as observed in: https://mapzen.com/documentation/search/autocomplete/
> Adds in missing query params for the autocomplete service

- addresses.md
This adds a section to the existing topic on searching for addresses, which we wrote for the libpostal integration. I think this is really the only location where we need to discuss interpolation, as I didn't really see a specific place for it in search or search/structured.
- Adds section on interpolation
- Adds API responses on accuracy/match_type to add interpolation
- Adds a random example
I wasn't exactly clear on whether we use straight line interpolation at all, or if it's always the "accentuate the curves" way because it considers the street geometry (which is how I wrote it). 
Take a look @dianashk @missinglink @orangejulius! Thanks!
> Add interpolation documentation

- language-codes.md
This has some edits and formatting to the docs in @missinglink's `request-language` branch. Please review my suggestions, and when they are ready, we can merge my branch into that branch (not master). Thanks for the draft -- it's good!
Sum:
- made some formatting edits and changes to headings (such as imperative verbs and second person)
- moved around some of the intro and tried not to use "default" as much (it's so hard!)
- moved the precedence section to the part where it talks about both methods
- added link to standard code document
To do:
- add working examples and links 
- explain how this affects the map/add links for how to set language on the map itself (if you are using search in conjunction with Mapzen maps, you may think this updates the language on the map)
- explain what …
> Some edits and formatting to language docs

- place.md
This came about because a user was using the demo on the Mapzen Search site and the result is interpolated. The demo always assumes a gid exists, which is confusing for interpolated results.
This modifies the sentence that indicates that ALL search results have gids, and adds a note that you cannot use place with interpolated results.
cc @missinglink - have a look!
> Add note about interpolated results and gids

- api-keys-rate-limits.md
- http-status-codes.md
We have a central topic in the main documentation that should now be the source for all info about rate limits and API keys. 
This adds a deprecation note to the API keys page here, removes other references to rate limits and errors. 
This page no longer publishes to mapzen.com (see https://github.com/mapzen/documentation/pull/289) We can keep the source md file in GitHub for now, similar to other pages that have been deprecated.
Part of https://github.com/mapzen/documentation/issues/192
> Standardize API key language, add deprecation note to API keys page here

- add-search-to-a-map.md
The tutorial was broken because it did not set an API key for the basemap vector tiles and the map would not display. These changes fixes that, as well as makes other updates to the content for mapzen.js.
Note: These issues were found while searching the docs for https://github.com/mapzen/documentation/issues/192, but is not dependent on that work and can be merged separately after a content review.
- adds a global API key from mapzen.js to support vector tiles and geocoding
- removes a Tangram scene option for the mapzen.js basemap that is being deprecated and gave a console warning
- updates how the geocoder passes options to match https://mapzen.com/documentation/mapzen-js/search/#options
- updates mapzen-xxxxx placeholder for preferred your-mapzen-api-key
- adds link to developer …
> Update tutorial for API key requirement and mapzen.js changes

- reverse.md
An example query in the reverse docs was listed after a giant table of
all possible layers values, which was a little confusing. This moves the
example query to right after the text describing it, and adds a little
more context for the table.
> Reorder part of the reverse documentation

- autocomplete.md
- place.md
- response.md
- reverse.md
- search.md
- structured-geocoding.md
- use-cors.md
These changes mostly update the links to use the (awesome!) sandbox site, compared to the URL to the raw JSON response. This is done to make sure the links work following the requirement to use an API key with all requests.
I made a few other minor edits as I went through, such as typos, markdown formatting (there should be a space between a # and the text in a heading and a line break after a heading), and style to change mapzen-xxxxxx to the preferred variable of `your-mapzen-api-key`.
In some cases, these queries give different results now than what we have documented. I have noted those places and we can review later...this is slightly more than a find and replace exercise, but does not include significant content updates.
> Update sample request links to use sandbox

- autocomplete.md
- place.md
- response.md
- reverse.md
- search.md
- structured-geocoding.md
This updates the base URLs for https://mapzen.github.io/search-sandbox with https://mapzen.com/search/explorer in the example links to reflect the sandbox's new home on mapzen.com.
> replace all github.io with mapzen.com base urls in example request links

- search.md
This rolls back this commit, with a slight modification https://github.com/pelias/pelias-doc/commit/7a4c172b20e02b2a58a8a763983756c46d97aac2
in the production docs, it looks like this 
(we shouldn't use mapzen-(anything) in the samples because they might squeak through as legit...)
> Shorten API key example text to avoid wrapping

- reverse.md
fixes #196 
Copies these from search and adds in the default for boundary.circle.radius default from https://github.com/pelias/api/blob/master/query/reverse_defaults.js.
Are boundary.circle.lat and lon are actually user-specifiable for reverse? Perhaps boundary.circle.lat and lon are always going to be point.lat and point.lon and cannot be changed in a query because there is only one radius/no options for overlapping circles?
If so, I'll remove boundary.circle.lat/lon from here.
Sample result:
"point.lat": 48.858268,
"point.lon": 2.294471,
"boundary.circle.radius": 1,
"boundary.circle.lat": 48.858268, <-- these seem fall back to point.lat, lon, if I've specified something else for them
"boundary.circle.lon": 2.294471,
> Add boundary.circle parameters for reverse

- index.md
This updates the home page to remove a broken/redirecting link about rate limits and updates the language for "plug-in" to be more general with it being part of mapzen.js.
> update broken link for rate limits, remove plug-in language

- language-codes.md
fixes #202 
Note: the example for using a `lang=` query parameter needs to be a link to the Mapzen Search Explorer site, when we get languages added to the UI and it's working on endpoints (see https://github.com/mapzen/search-sandbox/issues/1)
> Add information about the response section for languages

- add-search-to-a-map.md
- search.md
Part of https://github.com/mapzen/documentation/issues/310
I deleted some text that describes how to use the placeholder text (like replace it with your real key) because the key is already replaced when signed in, and the pop-up over the text will be the call to action for users who are not signed in.
While in the tutorial, I added a bunch of indents to fix numbering problems in the output documentation. Ugh.
The placeholder text was correct and being replaced on dev for all the examples (the link href is actually the search explorer).
And also updated the string that keeps wrapping on /search.
> Update text referring to replacing key placeholders

- release-notes.md
This includes all the Mapzen Search relevant changes in https://github.com/pelias/pelias/pull/609
as well as one change from May that never was published.
> Relase notes for May, June and July 2017

- reverse.md
I wasn't sure if boundary.circle.lat and lon were used with /reverse when I submitted the previous edits: https://github.com/pelias/pelias-doc/pull/197
Using them now gives an error message, so I'm removing these parameters for sure.
`[WARNING] boundary.circle.lat/boundary.circle.lon are currently unsupported`
> remove boundary.circle.lat and lon for reverse

- response.md
The current page the docs link to for the geojson spec http://geojson.org/geojson-spec.html says it is obsolete and points to https://tools.ietf.org/html/rfc7946. 
This updates the link to the current site.
> changing geojson spec link to current site

- response.md
This adds some documentation about `name` and `label` based on a user question in mapzen.js repo regarding using these properties. 
https://github.com/mapzen/mapzen.js/issues/429
> Update label and add name property to response

- data-sources.md
Now that we plan to import share-alike data, we need to tell users where
they can find out which OpenAddresses data is actually share alike. The
state.txt file on the OpenAddresses website has that information.
> Update data-sources page for OpenAddresses share-alike data

- README.md
- glossary.md
- result_quality.md
At the request of many users, this PR adds some information on confidence scores and other properties to help determine result quality.
A little bit of cleanup, especially in the organization of the table of contents, was done along the way.
Fixes https://github.com/pelias/documentation/issues/220
> Add documentation on result quality and confidence scores

- README.md
- full_planet_considerations.md
- getting_started_install.md
- pelias_from_scratch.md
- requirements.md
- services.md
We have let the non-Docker installation docs linger for quite some time. This PR attempts to correct out of date info, and split the rather massive install guide into something more manageable.
It adds documents for:
- Getting started with Pelias, pointing people to the Docker setup as well as other documents
- a "Pelias from scratch" guide, based on the old install guide
- a full planet build specific document, with some performance recommendations
- A single document describing in depth all our services, including a handy chart of which services are needed for which functionality.
Once this is merged, we'll need to follow up with a PR to https://github.com/pelias/pelias/ to link to these files.
> Refresh installation docs

- README.md
- structured-geocoding.md
As this endpoint hasn't seen the same level of rigorous testing as the search endpoint, this tag should help set peoples expectations for the endpoint's functionality and performance.
> Add a `beta` tag to the structured endpoint

- pelias_from_scratch.md
We are in the process of deprecating the staging/production branches.
The first step is to keep the documentation up to date and ensure people switch as soon as possible.
Connects https://github.com/pelias/pelias/issues/749
> fix(install): Update documentation to use master branches

- autocomplete.md
- place.md
- response.md
- reverse.md
- search-workflows.md
- search.md
- structured-geocoding.md
This started out as a small PR to improve links on the `structured` endpoint docs, but quickly outgrew that description.
Included are fixes to:
- Add documentation for the new [boundary.gid](https://github.com/pelias/api/pull/1249) parameter
- remove all links that used the Mapzen Search Explorer tool, which has gone away with the [Mapzen shutdown](https://github.com/pelias/pelias/issues/703). The well-maintained and independently hosted [Pelias Compare app](http://pelias.github.io/compare/) is used instead.
- Improve the documentation of `focus.point`. It had some out of date technical details and did not do a good job of describing the "soft" nature of the query parameter.
- Remove any remaining mentions of Mapzen API keys. These were a relic of the days with this was really …
> Documentation improvements

- structured-geocoding.md
missing url encoding of '?' led to endless loop when opening https://pelias.github.io/compare/#/v1/search/structured?postalcode=87801
> fixed typo and endless loop in linked URL

- development/roadmap.md
- pelias_from_scratch.md
- requirements.md
This ensures all our documentation is consistent with support for ES5, and officially dropping support for ES2, as part of https://github.com/pelias/pelias/issues/461
> Use Elasticsearch 5 as the default version in docs

- release-notes.md
Pelias components (importers and services) are released individually, and we don't have a "complete" release. This isn't called out explicitly anywhere as far as I know, so we add it to the top of the release notes.
Closes https://github.com/pelias/documentation/issues/276
> Explain the Pelias release process
